version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/NOTE_APP
      - PORT=8080
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: NOTE_APP
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  frontend:
    build:
      context: ./frontend/note_app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL="http://backend:8080/api/v1"
    depends_on:
      - backend

volumes:
  db-data:
